### ISSUE TITLE
Ideas for a web page menu structure 

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/pcyl-web#22]
The attached .PDF document presents a notion of what the PCyl-web menu structure might look like.  Considering a likely loss of formatting if pasted directly into the issue, it was just easier to attach the .PDF file.

[WebPageMenus2018_07_13.pdf](https://github.com/thegrumpys/pcyl-web/files/2194591/WebPageMenus2018_07_13.pdf)

The menu structure (place-holder) will be available as part of PCyl-web milestone 0.2.  The menu functionality will be filled in as appropriate for each succeeding milestone.

__See and Edit the Markdown in the next comment in lieu of attaching more PDFs__

**Comment by 1fifoto** [comment]
# Ideas for a web page menu structure
## July 13, 2018
Current thinking has a conventional horizontal menu bar located at the top of the
page. Five main menu items should look like:

Sys-Name | File | Action | View | Help |
--- | --- | --- | --- | ---

Additional details are on the following pages.
* Sys-Name
  * Link to web site
  * File
  * Open
  * Save
  * Save As
  * ----
  * System Preferences
  * ----
  * {4 most recently opened designs}
* Action
  * Execute
  * Search
  * Seek
  * Select Size
  * Select Catalog
  * Trade
* View
  * Define Classes
  * Display Classes
  * Report
  * □ Static Quantities
  * □ Violations
* Help
  * Context Help F1
  * Help Index
  * Tutorial
  * About

### Sys-Name : Web site
This menu item provides a link to the public-facing web site. The link will open a new
browser tab.

### File : Open
This menu item is similar to the PCyl-CLI START command. Prior to first use of this
“open” menu item, the web page can display the “splash screen”, similar to what is
generated by the PCyl-CLI intro.js.

### File : Save
This menu item is similar to the PCyl-CLI Save command. It over-writes the most
recently opened design file (.DSN) or database record.

### File : Save As
This menu item is similar to the PCyl-CLI Save command. It creates a new design file
(.DSN) or database record.

### ---------------------------------------

### File : System Preferences
This is a feature to set system specific values, including much of what is done by the
PCyl-CLI SET command. Other, web-specific, items may be included. Web page
layout control should be handled in the View menu.

### -------------------------------------

### File : {4 most recently opened designs}
These menu entries are provided for user convenience.

### Action : Execute
This menu item will trigger the play-back of a previously recorded sequence. A popup
(?) can provide the user an opportunity to supply a (file?) name to specify the
sequence. Some mechanism, for example, user supplied pauses will likely be
necessary to allow the user to control the pace so as to observe what is happening.
Annotations / comments are probably necessary.
The process of creating play-back sequences (files?) is not required to be user
accessible.
If necessary, generic third party tools can be used to create and annotate play-back
recordings.

### Action : Search
This menu item invokes the Search … directly equivalent to the PCyl-CLI Search
command. There may also be a search button on the main page. This menu item is
provided primarily to maintain consistency.

### Action : Seek
This menu item invokes Seek … directly equivalent to the PCyl-CLI Seek command.
There may also be Seek button(s) on the main page. This menu item is provided
primarily to maintain consistency.

### Action : Select Size
This menu item allows a table look-up for a standard size of a specific Independent
Variable. It is similar to the PCyl-CLI SELECT command.
Action : Select Catalog
This menu item allows the selection of the “nearest” design from a catalog of
standard designs. It is similar to the PCyl-CLI SELECT CATALOG command.

### Action : Trade
This menu item provides a similar feature to the PCyl-CLI Trade command. One
possible implementation is to pop up a form where the user can specify a strategy
(radio buttons similar to the current 0 – 3), over-ride step size and decide to keep the
result or not.

### View : Define Classes
This menu item provides an ability to establish an “IOCLASS” for independent and
dependent variables.

### View : Display Classes
This menu item allows the user to specify a group of classes to be displayed. This
frequently requested feature can allow complex design problems to be “partitioned”
into sub-problems that map to sub-systems of the real world.

### View : Report
This menu item creates a .PDF file and invokes the system .PDF utility to display it.
Both generic (Independent & Dependent variables, constraint levels & violations, etc.)
as well as problem-specific data in problem-specific formats can be included in the
report. The user can use the features of the system .PDF utility in order to save the
file into the browser’s local file system.

### View : Static Quantities
A check in the checkbox will cause “static quantities” (previously known as
“constants”) to be displayed.

### View : Violations
A check in the checkbox will cause both constraint violations and the value of the
objective function to be displayed.

### Help : Context Help F1
This menu item opens a new browser tab containing a context-specific web page
describing the current task (for example, the Trade pop-up form). Hitting the F1 key
produces the same result.

### Help : Help Index
This menu item opens a new browser tab containing the index page for the Help subsystem.
All Help topics should be reachable through links on the index page.

### Help : Tutorial
This menu item provides the ability to select from a list of tutorial sessions which play
back similarly to the Action : Execute menu item.

### Help : About
This menu item provides software release and design model version information. It
also includes a link to the publicly-facing web site (a repeat of the sys-name link).

**Comment by grumpyinca** [comment]
I renamed View : Define Classes to Define Sub-Problems and View : Display Classes to Display Sub-Problems plus updated the narrative description of Display Sub-Problems.

**Comment by grumpyinca** [comment]
This discussion has been moved to:  [docs/design](https://thegrumpys.github.io/pcyl-web/design/menu "link to GitHub").

Closing.
